name = "nomina-sfvcyd"
main = ".open-next/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Static assets will be served automatically
assets = { directory = ".open-next/assets", binding = "ASSETS" }
